# Production-like overlay: fixed 80/443 binds (configure via .env).
# Ensure your .env contains:
#   TRAEFIK_PROTOCOL=https
#   LETSENCRYPT_ENABLED=true
#   LETSENCRYPT_EMAIL=you@example.com
#   DOMAIN=your.domain
services:
  traefik:
    ports:
      - "${TRAEFIK_HTTP_BIND_HOST:-0.0.0.0}:${TRAEFIK_HTTP_PORT:-80}:80"
      - "${TRAEFIK_HTTPS_BIND_HOST:-0.0.0.0}:${TRAEFIK_HTTPS_PORT:-443}:443"