apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rocketchat.fullname" . }}-config
  labels:
    {{- include "rocketchat.labels" . | nindent 4 }}
data:
  MONGO_URL: {{ .Values.externalMongodb.url | quote }}
  MONGO_OPLOG_URL: {{ .Values.externalMongodb.oplogUrl | quote }}
  ROOT_URL: {{ .Values.rocketchat.rootUrl | quote }}

  DEPLOY_METHOD: "docker"
  DEPLOY_PLATFORM: "kubernetes"
  INSTANCE_IP: ""

  MICROSERVICES_ENABLED: "false"
  FEDERATION_ENABLED: "false"

  ADMIN_USERNAME: {{ .Values.rocketchat.adminUsername | quote }}
  ADMIN_PASS: {{ .Values.rocketchat.adminPassword | quote }}
  ADMIN_EMAIL: {{ .Values.rocketchat.adminEmail | quote }}

  API_Enable_CORS: "true"
  API_Enable_Rate_Limiter: "false"
