{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "rocketchat.fullname" . }}-pdb
  labels:
    {{- include "rocketchat.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "rocketchat.selectorLabels" . | nindent 6 }}
{{- end }}
