# Traefik dynamic configuration (rendered via envsubst to files/traefik/dynamic.yml)
# Variables:
#   localhost            e.g. localhost or chat.example.com
#       e.g. grafana.example.com (optional)
#   /grafana      e.g. /grafana (optional if GRAFANA_DOMAIN is set)
#   http  http|https (controls TLS requirement)

http:
  middlewares:
    grafana-strip:
      stripPrefix:
        prefixes:
          - "/grafana"

  routers:
    rocketchat:
      rule: "Host(`localhost`)"
      entryPoints:
        - web
      service: rocketchat-svc
      middlewares: []

    grafana-path:
      rule: "Host(`localhost`) && PathPrefix(`/grafana`)"
      entryPoints:
        - web
      service: grafana-svc
      middlewares:
        - grafana-strip

    grafana-subdomain:
      rule: "Host(``)"
      entryPoints:
        - web
      service: grafana-svc
      middlewares: []

  services:
    rocketchat-svc:
      loadBalancer:
        servers:
          - url: "http://rocketchat:3000"

    grafana-svc:
      loadBalancer:
        servers:
          - url: "http://grafana:3000"