global:
  scrape_interval: 30s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: node
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: mongodb
    static_configs:
      - targets: ["mongodb-exporter:9216"]

  - job_name: rocketchat
    static_configs:
      - targets: ["rocketchat:9458"]

  - job_name: traefik
    static_configs:
      - targets: ["traefik:9096"]
