name: Deploy ACA (single region)

on:
  workflow_dispatch:
    inputs:
      rocketchat_tag:
        description: "Rocket.Chat image tag (e.g., 7.9.2)"
        required: true
        default: "7.9.2"

permissions:
  id-token: write   # OIDC for azure/login
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy ACA stack (UK South)
        env:
          GRAFANA_ADMIN_PASSWORD: ${{ secrets.GRAFANA_ADMIN_PASSWORD }}
        run: |
          bash azure/deploy-aca.sh "${{ inputs.rocketchat_tag }}"

      - name: Show Rocket.Chat FQDN
        run: |
          az containerapp show -g Rocketchat_RG -n rocketchat --query properties.configuration.ingress.fqdn -o tsv || true
