name: Update Rocket.Chat in ACA

on:
  workflow_dispatch:
    inputs:
      rocketchat_tag:
        description: "Rocket.Chat image tag to deploy (e.g., 7.9.3)"
        required: true
        default: "7.9.3"
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Determine Rocket.Chat tag
        id: tag
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            # Expect release tag like rc-7.9.3 or v7.9.3; extract version
            ver=$(echo "${{ github.event.release.tag_name }}" | sed -E 's/^rc-|^v-?|^v//')
            echo "tag=$ver" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ inputs.rocketchat_tag }}" >> $GITHUB_OUTPUT
          fi

      - name: Update Rocket.Chat to tag
        run: |
          bash azure/update-rocketchat.sh "${{ steps.tag.outputs.tag }}"

      - name: Print revisions
        run: |
          az containerapp revision list -g Rocketchat_RG -n rocketchat -o table || true
